# Generated by Django 3.2 on 2021-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('pages', models.IntegerField(default=0, null=True)),
                ('description', models.CharField(default='', max_length=100, null=True)),
                ('author', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
