# Generated by Django 3.2 on 2021-06-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
